name: End-to-end tests

on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: e2e-main
  cancel-in-progress: true

jobs:
  e2e-tool-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      - name: Check out Ops
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
          repository: canonical/operator
          ref: main
          fetch-depth: 1
          path: operator
      - name: Run httpbin-demo
        working-directory: operator/examples/httpbin-demo
        run: uvx --with git+https://github.com/dwilding/jjx@main jjx -d -p 8000:80 -- -vv
      - name: Check workload
        run: curl --fail http://localhost:8000/
      - name: Tear down
        working-directory: operator/examples/httpbin-demo
        run: uvx --with git+https://github.com/dwilding/jjx@main jjx down
      - name: Check no workload
        run: |
          if curl --fail --max-time 2 http://localhost:8000/; then
            echo "ERROR: workload is still running after jjx down"
            exit 1
          fi
          echo "Workload is down (expected)"

  e2e-tool-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      - name: Check out Ops
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
          repository: canonical/operator
          ref: main
          fetch-depth: 1
          path: operator
      - name: Test httpbin-demo
        working-directory: operator/examples/httpbin-demo
        run: |
          touch placeholder.charm
          uv run --group integration --with git+https://github.com/dwilding/jjx@main pytest tests/integration

  e2e-dep-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      - name: Check out Ops
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
          repository: canonical/operator
          ref: main
          fetch-depth: 1
          path: operator
      - name: Add jjx to httpbin-demo
        working-directory: operator/examples/httpbin-demo
        run: uv add --group integration "jjx @ git+https://github.com/dwilding/jjx@main"
      - name: Run httpbin-demo
        working-directory: operator/examples/httpbin-demo
        run: uv run jjx -d -p 8000:80 -- -vv
      - name: Check workload
        run: curl --fail http://localhost:8000/
      - name: Tear down
        working-directory: operator/examples/httpbin-demo
        run: uv run jjx down
      - name: Check no workload
        run: |
          if curl --fail --max-time 2 http://localhost:8000/; then
            echo "ERROR: workload is still running after jjx down"
            exit 1
          fi
          echo "Workload is down (expected)"

  e2e-dep-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      - name: Check out Ops
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
          repository: canonical/operator
          ref: main
          fetch-depth: 1
          path: operator
      - name: Add jjx to httpbin-demo
        working-directory: operator/examples/httpbin-demo
        run: uv add --group integration "jjx @ git+https://github.com/dwilding/jjx@main"
      - name: Test httpbin-demo
        working-directory: operator/examples/httpbin-demo
        run: |
          touch placeholder.charm
          uv run --group integration pytest tests/integration
