name: Publish

on:
  push:
    tags:
      - "[0-9]+.*"

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish-jjx
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          enable-cache: false  # Avoid cache poisoning when publishing.
      - name: Build package
        run: uv build
      - name: Attest package provenance
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: "dist/*"
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
